// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchPaperKnowledgeWorkspace.Infrastructure.Data;

#nullable disable

namespace ResearchPaperKnowledgeWorkspace.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ResearchWorkspaceDbContext))]
    [Migration("20260619102101_AddDocumentImportSystem")]
    partial class AddDocumentImportSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFileAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceModifiedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentType");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("PaperId");

                    b.HasIndex("Sha256Hash")
                        .IsUnique();

                    b.ToTable("Attachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_FileSizeBytes", "\"FileSizeBytes\" >= 0");

                            t.HasCheckConstraint("CK_Attachments_PageCount", "\"PageCount\" IS NULL OR \"PageCount\" >= 0");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Affiliation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Orcid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("Orcid");

                    b.HasIndex("SortName");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedAuthorText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PaperId");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("Status");

                    b.ToTable("ImportJobs", (string)null);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastEditedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsPinned");

                    b.HasIndex("LastEditedAtUtc");

                    b.HasIndex("NoteType");

                    b.HasIndex("PaperId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AbstractText")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitationKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConferenceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Doi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issn")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JournalTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastOpenedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageRange")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PublicationDate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CitationKey");

                    b.HasIndex("Doi");

                    b.HasIndex("IsArchived");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("PublicationYear");

                    b.HasIndex("ReadingStatus");

                    b.HasIndex("Title");

                    b.ToTable("Papers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Papers_Priority", "\"Priority\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_Papers_PublicationYear", "\"PublicationYear\" IS NULL OR (\"PublicationYear\" BETWEEN 1000 AND 9999)");

                            t.HasCheckConstraint("CK_Papers_Rating", "\"Rating\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperAuthor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContributionRole")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrespondingAuthor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PaperId", "AuthorId")
                        .IsUnique();

                    b.HasIndex("PaperId", "AuthorOrder");

                    b.ToTable("PaperAuthors", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperAuthors_AuthorOrder", "\"AuthorOrder\" >= 1");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourcePaperId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetPaperId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationType");

                    b.HasIndex("SourcePaperId");

                    b.HasIndex("TargetPaperId");

                    b.HasIndex("SourcePaperId", "TargetPaperId", "RelationType")
                        .IsUnique();

                    b.ToTable("PaperRelations", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperRelations_Confidence", "\"Confidence\" BETWEEN 0.0 AND 1.0");

                            t.HasCheckConstraint("CK_PaperRelations_DifferentPapers", "\"SourcePaperId\" <> \"TargetPaperId\"");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentSource")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentSource");

                    b.HasIndex("TagId");

                    b.HasIndex("PaperId", "TagId")
                        .IsUnique();

                    b.ToTable("PaperTags", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperTags_Confidence", "\"Confidence\" BETWEEN 0.0 AND 1.0");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ProjectPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaperId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectSpecificNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("ResearchProjectId", "PaperId")
                        .IsUnique();

                    b.HasIndex("ResearchProjectId", "SortOrder");

                    b.ToTable("ProjectPapers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectPapers_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ResearchProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetCompletionAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("ResearchProjects", (string)null);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTagId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("ParentTagId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Attachment", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "Paper")
                        .WithMany("Attachments")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ImportJob", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Note", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "Paper")
                        .WithMany("Notes")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperAuthor", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Author", "Author")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperRelation", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "SourcePaper")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("SourcePaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "TargetPaper")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("TargetPaperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePaper");

                    b.Navigation("TargetPaper");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.PaperTag", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "Paper")
                        .WithMany("PaperTags")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Tag", "Tag")
                        .WithMany("PaperTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ProjectPaper", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", "Paper")
                        .WithMany("ProjectPapers")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.ResearchProject", "ResearchProject")
                        .WithMany("ProjectPapers")
                        .HasForeignKey("ResearchProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paper");

                    b.Navigation("ResearchProject");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Tag", b =>
                {
                    b.HasOne("ResearchPaperKnowledgeWorkspace.Core.Entities.Tag", "ParentTag")
                        .WithMany("ChildTags")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Author", b =>
                {
                    b.Navigation("PaperAuthors");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Paper", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("IncomingRelations");

                    b.Navigation("Notes");

                    b.Navigation("OutgoingRelations");

                    b.Navigation("PaperAuthors");

                    b.Navigation("PaperTags");

                    b.Navigation("ProjectPapers");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.ResearchProject", b =>
                {
                    b.Navigation("ProjectPapers");
                });

            modelBuilder.Entity("ResearchPaperKnowledgeWorkspace.Core.Entities.Tag", b =>
                {
                    b.Navigation("ChildTags");

                    b.Navigation("PaperTags");
                });
#pragma warning restore 612, 618
        }
    }
}
